language: go
sudo: false

go:
- 1.12

branches:
  only:
  - master


before_install:
  - go get -v -u github.com/valyala/gozstd
  - go get -v -u github.com/sirupsen/logrus
  - go get -v -u github.com/onrik/logrus/filename
  - go get -v -u github.com/pierrec/lz4
install: true

script:
  - ls
  - go build
  - ls
